name: 'Base64 to file'
description: 'Reads a base64 encoded content into a file'
author: 'Dzhunet Hasan'
branding:
  icon: 'settings'
  color: 'white'

inputs:
  encodedString:  
    description: 'The base64 encoded string'
    required: true
  destinationFileName:  
    description: 'Name of the file when written to temp location'
    required: true 
  destinationPath:  
    description: 'If it is set, change the output location to specific one from temp location.'
    required: true


outputs:
  filePath:
    description: 'The created temp file location'

runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.encodedString }} > ./${{ inputs.destinationFileName }}.tmp
      shell: bash
    - run: base64 -d -i ./${{ inputs.destinationFileName }}.tmp > ./${{ inputs.destinationFileName }}
      shell: bash
    - run: rm ./${{ inputs.destinationFileName }}.tmp
      shell: bash
    - run: mkdir -p ${{ inputs.destinationPath }}
      shell: bash
    - run: |
        DESTINATION_FILE=${{ inputs.destinationPath }}/${{ inputs.destinationFileName }}
        mv ./${{ inputs.destinationFileName }} ${{ inputs.destinationPath }}
        echo "filePath=$DESTINATION_FILE" >> "$GITHUB_OUTPUT"
        echo Base64 file generated as $DESTINATION_FILE
      shell: bash
